### PR TITLE
Made boost presence optional on Creep.body() calls

### LINKED ISSUE #245: Creep::body fails when parts aren't boosted
This line:

```rust
            let boost_v =
                js!(return __resource_type_str_to_num(@{self.as_ref()}.body[@{i}].boost););
```

Will throw an error, since `__resource_type_str_to_num` always requires valid input.

### PR DESCRIPTION
**Pull request by Dessix**
Fixes #245.

### CODE REVIEW

File: src/objects/impls/creep.rs [hunk 1]
```diff
@@ -27,7 +27,7 @@ impl Creep {
 
         for i in 0..len {
             let boost_v =
-                js!(return __resource_type_str_to_num(@{self.as_ref()}.body[@{i}].boost););
+                js!(const b=@{self.as_ref()}.body[@{i}].boost||null;return b&&__resource_type_str_to_num(b););
```
Comment (ASalvail) [inline src/objects/impls/creep.rs]: I'm nitpicking, but the line is fairly long...
